'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("capaPresentacion.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994339_talk_chat_message_comment_speak() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994339_talk_chat_message_comment_speak", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994340_diagram_pie_chart_circle_chart_graph_graphic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994340_diagram_pie chart_circle chart_graph_graphic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994341_graphic_pie_chart_circle_chart_graph_diagram() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994341_graphic_pie chart_circle chart_graph_diagram", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994342_alarm_clock_watch_hour_time() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994342_alarm_clock_watch_hour_time", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994343_sharing_cloud_server_network_cloud_computing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994343_sharing_cloud_server_network_cloud computing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994344_data_server_cloud_storage_network() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994344_data_server_cloud_storage_network", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994345_server_backup_upload_storage_cloud() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994345_server_backup_upload_storage_cloud", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994346_programming_code_coding_css_html() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994346_programming_code_coding_css_html", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994347_computer_desktop_screen_monitor_display() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994347_computer_desktop_screen_monitor_display", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994348_credit_card_finance_banking_payment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994348_credit_card_finance_banking_payment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994349_server_storage_hosting_data_center_database() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994349_server_storage_hosting_data center_database", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994350_mouse_click_cursor_pointer_select() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994350_mouse_click_cursor_pointer_select", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994351_remove_negative_close_minus_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994351_remove_negative_close_minus_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994352_bad_vote_thumbs_down_dislike_unlike() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994352_bad_vote_thumbs down_dislike_unlike", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994353_dollar_currency_banking_money_finance() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994353_dollar_currency_banking_money_finance", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994354_interface_download_save_downloading_interface_arrow_downloading_arrow_save_download() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994354_interface_download_save_downloading_interface_arrow_downloading_arrow_sav"& _ 
                        "e_download", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994355_downward_arrow_navigation_down_bottom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994355_downward_arrow_navigation_down_bottom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994356_earphone_headset_listen_headphone_dj() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994356_earphone_headset_listen_headphone_dj", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994357_drawer_archive_documents_files_office() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994357_drawer_archive_documents_files_office", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994358_dropper_eyedropper_pipette_color_picker_sample() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994358_dropper_eyedropper_pipette_color picker_sample", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994359_european_finance_currency_euro_money() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994359_european_finance_currency_euro_money", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994360_shrink_fullscreen_exit_fullscreen_interface_minimize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994360_shrink_fullscreen_exit fullscreen_interface_minimize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994361_rate_like_bookmark_favorite_star() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994361_rate_like_bookmark_favorite_star", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994362_data_paper_document_file_interface() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994362_data_paper_document_file_interface", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994363_sorting_filter_arrange_funnel_sort() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994363_sorting_filter_arrange_funnel_sort", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994364_archive_directory_organize_document_folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994364_archive_directory_organize_document_folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994365_mark_flag_banner_label_pin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994365_mark_flag_banner_label_pin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994366_team_members_people_group_friend() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994366_team_members_people_group_friend", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994367_full_fullscreen_expand_screen_maximize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994367_full_fullscreen_expand_screen_maximize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994368_tracking_position_navigation_positioning_gps() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994368_tracking_position_navigation_positioning_gps", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994369_profit_target_success_goal_business() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994369_profit_target_success_goal_business", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994370_business_growth_statistics_statistics_up_business_progress_progress_up_growth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994370_business_growth_statistics_statistics_up_business_progress_progress_up_gr"& _ 
                        "owth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994371_invisible_eye_private_hide_hidden() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994371_invisible_eye_private_hide_hidden", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994372_creativity_light_bulb_business_idea_brainstroming() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994372_creativity_light bulb_business_idea_brainstroming", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994373_house_main_home_interface_menu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994373_house_main_home_interface_menu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994374_mailbox_email_mailbox_inbox_message_email_incoming_mail_incoming_mail_message_inbox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994374_mailbox_email_mailbox_inbox_message_email_incoming mail_incoming mail_mes"& _ 
                        "sage_inbox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994375_info_faq_help_information_about() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994375_info_faq_help_information_about", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994376_previous_arrow_left_back_navigation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994376_previous_arrow_left_back_navigation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994377_favorite_thumbs_up_vote_good_like() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994377_favorite_thumbs up_vote_good_like", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994378_map_navigation_location_pin_position() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994378_map_navigation_location_pin_position", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994379_lock_security_padlock_privacy_protection() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994379_lock_security_padlock_privacy_protection", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994380_sign_in_login_enter_input_access() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994380_sign in_login_enter_input_access", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994380_sign_in_login_enter_input_access1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994380_sign in_login_enter_input_access1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994381_bankruptcy_down_loss_failure_statistics() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994381_bankruptcy_down_loss_failure_statistics", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994382_close_access_sign_out_exit_logout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994382_close_access_sign out_exit_logout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994383_mail_email_newsletter_envelope_letter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994383_mail_email_newsletter_envelope_letter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994384_map_world_travel_local_location() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994384_map_world_travel_local_location", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994385_message_note_sticky_notes_memo_reminder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994385_message_note_sticky notes_memo_reminder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994386_dollar_money_payment_finance_cash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994386_dollar_money_payment_finance_cash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994387_bubble_message_sms_text_chat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994387_bubble_message_sms_text_chat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994388_detail_interface_interface_more_list_detail_menu_more_list_menu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994388_detail_interface_interface_more_list_detail_menu_more_list_menu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994389_move_drag_cursor_drop_pointer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994389_move_drag_cursor_drop_pointer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994390_headline_newspaper_article_journal_news() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994390_headline_newspaper_article_journal_news", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994391_alert_notify_reminder_bell_notification() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994391_alert_notify_reminder_bell_notification", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994392_document_news_article_journal_paper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994392_document_news_article_journal_paper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994393_shutdown_off_on_switch_power() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994393_shutdown_off_on_switch_power", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994394_pin_marker_label_pushpin_thumbtack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994394_pin_marker_label_pushpin_thumbtack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994395_write_pen_pencil_stationery_edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994395_write_pen_pencil_stationery_edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994396_faq_help_ask_mark_question() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994396_faq_help_ask_mark_question", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994397_printing_paper_printer_print_offset() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994397_printing_paper_printer_print_offset", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994398_feed_rss_media_blog_news() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994398_feed_rss_media_blog_news", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994399_repeat_refresh_reload_sync_rotate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994399_repeat_refresh_reload_sync_rotate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994400_forward_navigation_right_next_arrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994400_forward_navigation_right_next_arrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994401_search_zoom_find_magnifier_magnifying_glass() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994401_search_zoom_find_magnifier_magnifying glass", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994402_interface_send_message_paper_plane_sent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994402_interface_send_message_paper plane_sent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994403_options_cog_gear_preferences_settings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994403_options_cog_gear_preferences_settings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994404_send_network_share_publish_social_media() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994404_send_network_share_publish_social media", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994405_security_antivirus_protection_insurance_shield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994405_security_antivirus_protection_insurance_shield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994406_show_on_eye_view_visible() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994406_show_on_eye_view_visible", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994407_microphone_radio_mic_record_sound_recorder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994407_microphone_radio_mic_record_sound recorder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994408_business_management_teamwork_plan_strategy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994408_business_management_teamwork_plan_strategy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994409_music_sound_volume_speaker_audio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994409_music_sound_volume_speaker_audio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994410_delete_garbage_recycle_bin_dustbin_trash_can() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994410_delete_garbage_recycle bin_dustbin_trash can", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994411_television_display_screen_technology_tv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994411_television_display_screen_technology_tv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994412_unlock_password_lock_key_open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994412_unlock_password_lock_key_open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994413_arrow_above_up_navigation_top() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994413_arrow_above_up_navigation_top", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994414_interface_send_upload_uploading_arrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994414_interface_send_upload_uploading_arrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994415_user_account_profile_person_avatar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994415_user_account_profile_person_avatar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994416_camera_camcorder_video_camera_movie_record() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994416_camera_camcorder_video camera_movie_record", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994417_money_wallet_purse_cash_purchase() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994417_money_wallet_purse_cash_purchase", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994418_network_wireless_signal_internet_wifi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994418_network_wireless_signal_internet_wifi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994419_web_internet_world_www_global() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994419_web_internet_world_www_global", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994420_write_new_pen_draw_edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994420_write_new_pen_draw_edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994421_enlarge_magnifying_zoom_in_magnifier_glass() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994421_enlarge_magnifying_zoom in_magnifier_glass", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994422_zoom_out_magnifier_magnifying_search_glass() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994422_zoom out_magnifier_magnifying_search_glass", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994423_checkmark_yes_correct_done_complete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994423_checkmark_yes_correct_done_complete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994424_remove_delete_close_cancel_reject() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994424_remove_delete_close_cancel_reject", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994425_interface_photography_photo_lens_camera() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994425_interface_photography_photo_lens_camera", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994426_event_month_calendar_schedule_date() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994426_event_month_calendar_schedule_date", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994427_malware_insect_bug_virus_pest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994427_malware_insect_bug_virus_pest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994428_website_web_internet_window_browser_window_internet_browser_web() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994428_website_web_internet_window_browser_window_internet_browser_web", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994429_bag_business_briefcase_suitcase_portfolio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994429_bag_business_briefcase_suitcase_portfolio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994430_save_web_bookmark_label_ribbon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994430_save_web_bookmark_label_ribbon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994431_bluetooth_connection_wireless_signal_device() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994431_bluetooth_connection_wireless_signal_device", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994432_book_textbook_notebook_guidebook_literature() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994432_book_textbook_notebook_guidebook_literature", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994433_clip_attach_office_paperclip_attachment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994433_clip_attach_office_paperclip_attachment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994434_email_at_email_address_contact_address_at_contact() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994434_email_at_email_address_contact_address_at_contact", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994435_ban_disabled_stop_banned_block() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994435_ban_disabled_stop_banned_block", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994436_promotion_marketing_megaphone_bullhorn_advertising() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994436_promotion_marketing_megaphone_bullhorn_advertising", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994437_create_positive_add_plus_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994437_create_positive_add_plus_new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3994438_download_cloud_server_storage_network() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3994438_download_cloud_server_storage_network", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cart1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cart1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cart2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cart2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
